import * as THREE from 'three';
import type { ActionConsumedBy, GameInputAction, InputMode } from '../game/InputActionRouter';

/** How often the published diagnostics snapshot is refreshed. */
const PUBLISH_INTERVAL_SECONDS = 0.1;

export type ArcaDiagnostics = {
  fps: number;
  drawCalls: number;
  triangles: number;
  activeParticles: number;
  entryParticles: number;
  surfaceParticles: number;
  activePOIs: number;
  activeThreats: number;
  dialogueQueueLength: number;
  currentDialogueId: string;
  currentSpeaker: string;
  currentDialoguePriority: string;
  playedDialogueCount: number;
  lastDialogueTrigger: string;
  dialoguePanelVisible: boolean;
  dialogueAwaitingInput: boolean;
  activeGLBCount: number;
  activeSkinnedMeshCount: number;
  activeAnimationMixerCount: number;
  activeHighPolyAssets: string[];
  duplicateMeshWarnings: string[];
  heavyAssetWarnings: string[];
  bundleWarning: string;
  estimatedDrawCalls: number;
  inactiveUpdateSkippedCounts: Record<string, number>;
  lodActive: boolean;
  lodLevelCharacter: string;
  lodLevelCockpit: string;
  lodHiddenInactiveAssets: number;
  atlasLodLevel: string;
  arcaLodLevel: string;
  shipLodLevel: string;
  cockpitLodLevel: string;
  pilotLodLevel: string;
  activeTriangleEstimate: number;
  assetPreloadQueue: string[];
  assetLoadState: Record<string, string>;
  lazyLoadedAssets: string[];
  preloadCompleted: boolean;
  mothershipStatus: string;
  mothershipPath: string;
  mothershipMeshCount: number;
  mothershipTriangles: number;
  mothershipScale: number;
  mothershipVisible: boolean;
  playerShipStatus: string;
  playerShipPath: string;
  playerShipMeshCount: number;
  playerShipTriangles: number;
  playerShipScale: number;
  playerShipVisible: boolean;
  shipPosition: [number, number, number];
  shipVelocity: [number, number, number];
  shipAltitudeHold: number;
  shipGroundClearance: number;
  shipAltitudeHoldTarget: number;
  shipVerticalVelocity: number;
  shipRealY: number;
  shipPreviousY: number;
  shipAltitudeHoldY: number;
  shipTerrainY: number;
  shipTerrainClearance: number;
  parkedShipTerrainHeight: number;
  parkedShipHullBottom: number;
  parkedShipTerrainSeparation: number;
  shipBoardingAnchorWorld: [number, number, number];
  shipBoardingHorizontalDistance: number;
  shipBoardingVerticalDifference: number;
  shipBoardingAvailable: boolean;
  shipParked: boolean;
  surfaceZone: 'space' | 'nereida' | 'aurora' | 'surface-transit';
  shipParkingState: 'flight' | 'transition' | 'parked';
  parkedShipClearanceTarget: number;
  shipVisualOscillationActive: boolean;
  shipAccessFConsumed: boolean;
  parkedShipRestoreChecked: boolean;
  parkedShipSaveCorrected: boolean;
  playerShipInstances: number;
  shipAltitudeResetForce: number;
  shipCameraJumpDistance: number;
  verticalThrustActive: boolean;
  shipCollisionCollidersActive: number;
  shipCollisionSweptDistance: number;
  shipCollisionImpact: boolean;
  shipCollisionTimeOfImpact: number;
  shipCollisionNormal: [number, number, number];
  shipCollisionPenetration: number;
  shipCollisionObject: string;
  shipCollisionCandidates: number;
  shipCollisionSubsteps: number;
  shipCollisionLastSafePosition: [number, number, number];
  orbitalMarkerStatus: string;
  orbitalMarkerPath: string;
  orbitalMarkerMeshCount: number;
  orbitalMarkerMaterialCount: number;
  orbitalMarkerTriangles: number;
  orbitalMarkerObjectCount: number;
  orbitalMarkerScale: number;
  orbitalMarkerVisible: boolean;
  orbitalMarkerLodLevel: string;
  descentPhase: string;
  descentProgress: number;
  descentHeat: number;
  descentStability: number;
  descentAltitude: number;
  mission01Step: string;
  orbitalScanComplete: boolean;
  habitabilityScore: number;
  missingDescentRequirements: string[];
  descentAuthorized: boolean;
  descentBlockedReason: string;
  atlasCorridorDecoded: boolean;
  altitudeEstimate: number;
  descentSpeedEstimate: number;
  heatLevel: number;
  turbulenceLevel: number;
  entryFxIntensity: number;
  /** Atmospheric-entry stage: exosphere → contact → peak → descent → approach. */
  entryStage: string;
  entryHeat: number;
  entryIonization: number;
  entryHaze: number;
  /**
   * Raw buffet from the entry profile, before the camera easing in
   * `turbulenceLevel`. The two differ on purpose: this is the design curve,
   * that one is what the camera actually feels.
   */
  entryBuffet: number;
  /** Air density 0..1 — the one driver that only ever increases. */
  entryAirDensity: number;
  landingZoneActive: boolean;
  corridorPipsVisible: boolean;
  basinReveal: number;
  landingImpactVisible: boolean;
  horizonTriangles: number;
  cameraMode: 'external' | 'cockpit';
  previousShipCameraPreference: 'external' | 'cockpit';
  cameraFollowInitialized: boolean;
  cameraTargetCurrent: [number, number, number];
  cameraTargetPrevious: [number, number, number];
  cameraJumpDistance: number;
  /** Vertical FOV in degrees. Watched during the entry choreography. */
  cameraFov: number;
  lastCameraModeTransition: string;
  cockpitActive: boolean;
  cockpitGlbStatus: 'loading' | 'loaded' | 'fallback' | 'error';
  cockpitGlbPath: string;
  cockpitGlbMeshCount: number;
  cockpitGlbMaterialCount: number;
  cockpitGlbTriangleCount: number;
  cockpitGlbScale: number;
  cockpitDrawCalls: number;
  cockpitScreenUpdateRate: number;
  cockpitScreenCount: number;
  cockpitUpdateSkippedWhenInactive: number;
  cockpitTextureUpdateCount: number;
  cockpitScreenAnchorsVisible: boolean;
  cockpitDustParticleCount: number;
  cockpitActiveDustParticles: number;
  cockpitCanopyReflectionOpacity: number;
  playerMode: 'SHIP_SPACE' | 'SHIP_SURFACE' | 'COCKPIT' | 'EXITING_SHIP' | 'ON_FOOT' | 'ENTERING_SHIP';
  onFootActive: boolean;
  characterGlbStatus: 'loading' | 'loaded' | 'fallback' | 'error';
  characterMeshCount: number;
  characterMaterialCount: number;
  characterTriangleCount: number;
  visibleCharacterMeshCount: number;
  activeCharacterSkinnedMeshCount: number;
  visibleCharacterTriangleCount: number;
  loadedAnimationSources: number;
  discardedDuplicateMeshes: number;
  characterClipCount: number;
  mixerActive: boolean;
  characterPerformanceWarning: string;
  characterAnimationClips: string[];
  characterAnimation: string;
  characterMoveState: string;
  characterInputVector: [number, number];
  characterVelocity: [number, number, number];
  characterFacingYaw: number;
  cameraYaw: number;
  cameraPitch: number;
  characterPosition: [number, number, number];
  characterSpeed: number;
  characterGrounded: boolean;
  characterColliderActive: boolean;
  characterCollisionSlope: number;
  characterCollisionContact: boolean;
  characterCollisionNormal: [number, number, number];
  characterCollisionPenetration: number;
  characterCollisionIterations: number;
  characterCollisionCandidates: number;
  characterCollisionLastSafePosition: [number, number, number];
  liftRideState: string;
  characterOnLift: boolean;
  characterFootLockActive: boolean;
  liftProgress: number;
  liftContactShadowActive: boolean;
  boardingAnimationState: string;
  nearestInteractionTarget: string;
  nearestInteractionAction: GameInputAction | 'none';
  interactionDistance: number;
  insideShip: boolean;
  rampState: 'retracted' | 'deploying' | 'deployed' | 'boarding';
  shipExitAvailable: boolean;
  shipAccessAvailable: boolean;
  inputMode: InputMode;
  lastInputKey: string;
  lastInputAction: GameInputAction | 'none';
  actionConsumedBy: ActionConsumedBy;
  canToggleCamera: boolean;
  cameraToggleAvailable: boolean;
  mapOpen: boolean;
  pauseOpen: boolean;
  currentPhase: string;
  currentMissionId: string;
  currentMissionStep: string;
  objectiveText: string;
  nextAction: string;
  currentGuideTarget: string;
  guideTargetName: string;
  guideTargetDistance: number;
  guideDirection: number;
  guideMode: string;
  guideDistance: number;
  guideVisible: boolean;
  guideOffscreen: boolean;
  guideSource: string;
  playerInputMode: string;
  surfaceModeActive: boolean;
  mission02Step: string;
  mission03Started: boolean;
  mission03Step: string;
  communicationCalibrated: boolean;
  communicationCalibrationProgress: number;
  mission03SignalState: string;
  relayBeaconPlaced: boolean;
  relayRange: number;
  signalStability: number;
  playerInRelayRange: boolean;
  relaySignalFlowActive: boolean;
  translationState: string;
  translationProgress: number;
  translatedFragments: number;
  pleyadanContactEstablished: boolean;
  hologramWarningActive: boolean;
  atlasTranslationMatrixUnlocked: boolean;
  galacticThreatKnown: boolean;
  orbitalDefenseRequired: boolean;
  mission04Unlocked: boolean;
  mission03Completed: boolean;
  mission04Started: boolean;
  mission04Step: string;
  defenseNetworkState: string;
  defensiveBeaconsPlaced: boolean[];
  defenseSyncProgress: number;
  activeDefenseBeaconTarget: number;
  threatSignatureDetected: boolean;
  mission04Completed: boolean;
  mission05Unlocked: boolean;
  defenseLinksActive: boolean;
  defenseLinksUnstable: boolean;
  defenseLinksOnline: boolean;
  defenseNetworkVisible: boolean;
  threatSignatureWorldVisible: boolean;
  activeDefenseLinkCount: number;
  mission05Started: boolean;
  mission05Step: string;
  probeState: string;
  interferenceActive: boolean;
  activeEchoIndex: number;
  echoesResolved: number;
  counterSignalProgress: number;
  probeRetreated: boolean;
  firstHostileContactConfirmed: boolean;
  mission06Unlocked: boolean;
  mission06Started: boolean;
  mission06Step: string;
  interferenceResidueAnalyzed: boolean;
  cloakingMatrixCalibrated: boolean;
  cloakingProjectorsPlaced: boolean[];
  cloakingProjectorsCalibrated: boolean[];
  cloakingSyncProgress: number;
  cloakingFieldOnline: boolean;
  nereidaSignatureReduced: boolean;
  mission06Completed: boolean;
  mission07Unlocked: boolean;
  mission07Started: boolean;
  mission07Step: string;
  subsurfaceSignalAnalyzed: boolean;
  atlasFractureRevealed: boolean;
  atlasEchoNodesScanned: boolean[];
  atlasSeedArchiveUnlocked: boolean;
  atlasSeedArchiveActivated: boolean;
  seedWorldRevealed: boolean;
  mission07Completed: boolean;
  mission08Unlocked: boolean;
  mission08Started: boolean;
  mission08Step: string;
  fractureTraceAnalyzed: boolean;
  signalFractureRevealed: boolean;
  fractureNodesStabilized: boolean[];
  signalPurgeProgress: number;
  signalFractureContained: boolean;
  coalitionTraceResidual: boolean;
  mission08Completed: boolean;
  mission09Unlocked: boolean;
  mission09Started: boolean;
  mission09Step: string;
  residualTraceAnalyzed: boolean;
  auroraRouteDecoded: boolean;
  auroraRouteBeaconsScanned: boolean[];
  currentAuroraSector: number;
  auroraSignalStrength: number;
  auroraSectorDiscovered: boolean;
  mission09Completed: boolean;
  mission10Unlocked: boolean;
  activeAuroraSectorCount: number;
  auroraSectorStreamingActive: boolean;
  premiumVisualsEnabled: boolean;
  premiumVisualsMode: string;
  premiumVisualQuality: string;
  premiumParticleCount: number;
  premiumVisualDrawCalls: number;
  premiumVisualWarnings: string[];
  webgpuAvailable: boolean;
  tslAvailable: boolean;
  premiumAutoQualityEnabled: boolean;
  premiumFpsAverage: number;
  premiumQualityDowngradeReason: string;
  premiumLastQualityChangeAt: number;
  /** Active render profile and the point-light budget it enforces. */
  renderProfile: string;
  activePointLights: number;
  registeredPointLights: number;
  mission13Started: boolean;
  mission13Step: string;
  auroraStormAlertAcknowledged: boolean;
  auroraGeneratorSecured: boolean;
  auroraGeneratorProgress: number;
  auroraAntennaAnchorsSecured: boolean[];
  auroraAntennaOnline: boolean;
  auroraShieldCharge: number;
  auroraShieldOnline: boolean;
  /** M13 front strength. Distinct from the M09 route's auroraStormIntensity. */
  auroraStormFrontIntensity: number;
  auroraStormEnergyStability: number;
  auroraStormInterference: number;
  mission13Completed: boolean;
  mission14Unlocked: boolean;
  // --- Mission 14: La Marca que Quedó ---
  mission14Started: boolean;
  mission14Step: string;
  coalitionTraceInspections: boolean[];
  coalitionSignatureAnalyzed: boolean;
  coalitionPowerNodePurged: boolean;
  coalitionCommsNodePurged: boolean;
  coalitionHiddenNodeLocated: boolean;
  coalitionTraceSampleRecovered: boolean;
  coalitionReverseTriangulationComplete: boolean;
  coalitionContamination: number;
  coalitionHostileTriangulation: number;
  coalitionSignalIntensity: number;
  coalitionPurgedNodes: number;
  coalitionPhaseProgress: number;
  coalitionTraceVisualActive: boolean;
  mission14Completed: boolean;
  mission15Unlocked: boolean;
  // --- Mission 15: Sabotaje en Aurora ---
  mission15Started: boolean;
  mission15Step: string;
  auroraRoutineComplete: boolean;
  auroraModuleSealed: boolean;
  auroraModuleReleased: boolean;
  auroraCoordinatedFailureConfirmed: boolean;
  auroraParasiteStates: string[];
  mission15Sequence: number[];
  mission15SequenceVisualStep: number;
  mission15SequenceLogicalStep: number;
  mission15ExpectedSymbol: number;
  mission15HighlightedSymbol: number;
  mission15InteractedSymbol: number;
  mission15SequenceMatched: number;
  mission15SequenceInputConsumed: boolean;
  mission15SequenceInputLockRemaining: number;
  mission15SequenceErrorActive: boolean;
  mission15SequenceFeedback: string;
  mission15SequenceCompleted: boolean;
  auroraParasitesFound: number;
  auroraParasitesDisabled: number;
  auroraModulePressure: number;
  auroraCompromisedSystems: number;
  auroraCentralOverload: number;
  auroraCentralOverloadResolved: boolean;
  auroraSabotageSignalIntensity: number;
  auroraSabotagePhaseProgress: number;
  auroraParasiteAnalyzed: boolean;
  auroraSabotageVisualActive: boolean;
  mission15Completed: boolean;
  mission16Unlocked: boolean;
  mission21Started: boolean;
  mission21Step: string;
  transmissionChannelsAligned: boolean[];
  transmissionDecoded: boolean;
  capitalShipDetected: boolean;
  capitalSignatureAnalyzed: boolean;
  ultimatumReceived: boolean;
  coalitionResponseTone: string;
  enclaveChannelsRestored: boolean[];
  demonstrationObserved: boolean;
  attackRoutesClassified: boolean[];
  pleyadianNetworkActivated: boolean;
  simultaneousAssaultDetected: boolean;
  mission21Completed: boolean;
  mission22Unlocked: boolean;
  coalitionCapitalPresenceBuilt: boolean;
  coalitionCapitalPresenceVisible: boolean;
  coalitionCapitalAttackable: boolean;
  coalitionRemoteBeaconDestroyed: boolean;
  coalitionAttackRoutesVisible: number;
  mission21InterferenceLevel: number;
  mission22Started: boolean;
  mission22Step: string;
  mission22AuroraIntegrity: number;
  mission22NereidaIntegrity: number;
  mission22OrbitalIntegrity: number;
  mission22InitialEnergyFront: string;
  mission22InitialDefenseFront: string;
  mission22InitialCommsFront: string;
  mission22AuroraFrontDefended: boolean;
  mission22NereidaFrontDefended: boolean;
  mission22OrbitalRelaysProtected: boolean[];
  mission22CrossFrontCrisisManaged: boolean;
  mission22SupportPriority: string;
  mission22JointNetworkRestored: boolean;
  mission22CoordinationNodesDetected: boolean[];
  mission22FinalPressureSurvived: boolean;
  mission22Completed: boolean;
  mission23Unlocked: boolean;
  mission22VisualBuilt: boolean;
  mission22VisualVisible: boolean;
  mission22VisibleRelayCount: number;
  mission22VisibleNodeCount: number;
  mission22JointNetworkVisible: boolean;
  mission23Started: boolean;
  mission23Step: string;
  mission23TargetOrder: string[];
  jointForcesSynchronized: boolean;
  jammerTriangulationReadings: boolean[];
  jammerNodeDestroyed: boolean;
  platformDefensesDisabled: boolean;
  platformEnergyDisabled: boolean;
  mission23PlatformMethod: string;
  logisticsPlatformDestroyed: boolean;
  jumpBeaconAnchorsDisabled: boolean[];
  jumpBeaconDestroyed: boolean;
  escapeCompleted: boolean;
  enemyRouteRecovered: boolean;
  returnToArkConfirmed: boolean;
  mission23Completed: boolean;
  mission24Unlocked: boolean;
  mission23JointEnergy: number;
  mission23LockDegraded: boolean;
  mission23PlatformBuilt: boolean;
  mission23PlatformVisible: boolean;
  mission23PlatformActiveModules: number;
  mission23JumpBeaconBuilt: boolean;
  mission23JumpBeaconVisible: boolean;
  mission23VisibleAnchorCount: number;
  mission23ActiveHostiles: number;
  mission23EscapeDistance: number;
  mission24Started: boolean;
  mission24Step: string;
  returnRouteDecoded: boolean;
  launchPrepared: boolean;
  shipBoardedForReturn: boolean;
  ignitionComplete: boolean;
  takeoffComplete: boolean;
  lowAtmosphereComplete: boolean;
  cloudLayerComplete: boolean;
  midAtmosphereComplete: boolean;
  upperAtmosphereComplete: boolean;
  vacuumTransitionComplete: boolean;
  orbitalInsertionComplete: boolean;
  orbitStabilized: boolean;
  mission24ArkReached: boolean;
  mission24ArkSystemsAssessed: number;
  mission24EnclaveLinksRestored: number;
  mission24ArkSystemsPrepared: number;
  mission24PleyadianNodesIntegrated: number;
  civilianSheltersPrepared: boolean;
  alliedForcesAssembled: boolean;
  startingSectorRevisited: boolean;
  defenseRehearsalComplete: boolean;
  finalFleetDetected: boolean;
  finalFormationEntered: boolean;
  mission24Completed: boolean;
  mission25Unlocked: boolean;
  mission24Altitude: number;
  mission24WorldClearance: number;
  mission24VerticalSpeed: number;
  mission24HorizontalSpeed: number;
  mission24Pressure: number;
  mission24Density: number;
  mission24Wind: number;
  mission24CloudOpacity: number;
  mission24StarOpacity: number;
  mission24Curvature: number;
  mission24OrbitalStability: number;
  mission24MaxFrameDisplacement: number;
  mission24Checkpoint: string;
  mission24AtmosphereBuilt: boolean;
  mission24CloudLayerVisible: boolean;
  mission24PlanetLimbVisible: boolean;
  mission24NetworkBuilt: boolean;
  mission24NetworkVisible: boolean;
  mission24PleyadianNodesVisible: number;
  mission24RehearsalTargets: number;
  mission24RehearsalTargetsVisible: boolean;
  mission24FinalFleetVisible: boolean;
  mission24FinalFleetAttackable: boolean;
  mission24ActiveTimers: number;
  mission24MothershipUuid: string;
  mission24MothershipInstances: number;
  mission25Started: boolean;
  mission25State: string;
  mission25DefensePhase: number;
  mission25Wave: number;
  mission25ArkIntegrity: number;
  mission25SystemIntegrities: number[];
  mission25InheritedM22Priority: string;
  mission25InheritedM23Support: boolean;
  mission25CommandNodesDestroyed: boolean[];
  mission25CommandCoreIntegrity: number;
  mission25ActiveEnemies: number;
  mission25EnemiesDestroyed: number;
  mission25BattleState: string;
  mission25EndingStarted: boolean;
  mission25EndingCompleted: boolean;
  mission25Completed: boolean;
  chapterCompleted: boolean;
  mission25DefenseNetworkBuilt: boolean;
  mission25DefenseNetworkVisible: boolean;
  mission25CommandBuilt: boolean;
  mission25CommandVisible: boolean;
  mission25ActiveTimers: number;
  mission25MothershipUuid: string;
  mission25MothershipInstances: number;
  mission25PlayerShipInstances: number;
  mission25MusicCue: string;
  mission25SaveRestored: boolean;
  mission12Started: boolean;
  mission12Step: string;
  auroraFirstCrewAuthorized: boolean;
  auroraLifeSupportHumanReady: boolean;
  auroraHabitationConfigured: boolean;
  auroraLandingZoneMarked: boolean;
  auroraCrewCapsuleLanded: boolean;
  auroraFirstCrewDisembarked: boolean;
  auroraHumanLoadProgress: number;
  auroraHumanLoadRecalibrated: boolean;
  auroraRecalibrationProgress: number;
  auroraInhabitedCoreStable: boolean;
  auroraFirstNightRecorded: boolean;
  mission12Completed: boolean;
  mission13Unlocked: boolean;
  currentCrewCount: number;
  habitationStability: number;
  mission11Started: boolean;
  mission11Step: string;
  auroraCoreDiagnosticComplete: boolean;
  auroraSecondModuleDeployed: boolean;
  auroraEnergyLinkOnline: boolean;
  auroraWaterFilterInstalled: boolean;
  auroraWaterFlowCalibrated: boolean;
  auroraCultivationBedPrepared: boolean;
  auroraBioTrialStarted: boolean;
  auroraImpactAssessmentComplete: boolean;
  auroraCoreOperational: boolean;
  mission11Completed: boolean;
  mission12Unlocked: boolean;
  mission10Started: boolean;
  mission10Step: string;
  auroraInitialSurveyComplete: boolean;
  auroraWaterAnalyzed: boolean;
  auroraSoilAnalyzed: boolean;
  auroraAtmosphereAnalyzed: boolean;
  auroraBioSafetyChecked: boolean;
  auroraSettlementSiteMarked: boolean;
  auroraModuleDeployed: boolean;
  auroraModuleOperational: boolean;
  auroraStabilizationProgress: number;
  mission10Completed: boolean;
  mission11Unlocked: boolean;
  currentAuroraTravelSegment: string;
  auroraMusicSegment: string;
  auroraEnvironmentalEvent: string;
  auroraEnvironmentalEventActive: boolean;
  auroraStormIntensity: number;
  auroraWindIntensity: number;
  auroraFogIntensity: number;
  auroraCinematicTravelActive: boolean;
  auroraRevealActive: boolean;
  signalFractureVisualActive: boolean;
  auroraRevealVisualActive: boolean;
  currentMusicState: string;
  currentMusicTrack: string;
  activeMusicLayers: string[];
  engineAudioState: string;
  propulsionIntensity: number;
  hoverAudioIntensity: number;
  verticalThrustAudioIntensity: number;
  boostAudioIntensity: number;
  groundWashAudioIntensity: number;
  spaceCruiseAudioActive: boolean;
  atmosphericAudioActive: boolean;
  interferenceAudioActive: boolean;
  dialogueDuckingActive: boolean;
  musicDuckingAmount: number;
  missingAudioAssets: string[];
  missingMusicAssets: string[];
  commanderVoiceEnabled: boolean;
  voiceManifestLoaded: boolean;
  currentVoiceDialogueId: string;
  voicePlaying: boolean;
  voiceMissingCount: number;
  pleyadanVoiceEnabled: boolean;
  commanderVoiceAvailableCount: number;
  pleyadanVoiceAvailableCount: number;
  voiceVolume: number;
  voiceDuckingActive: boolean;
  lastVoiceError: string;
  footstepAudioActive: boolean;
  footstepMode: string;
  lastFootstepTime: number;
  footstepSurface: string;
  footstepMissingAssets: string[];
  waterStatus: string;
  mineralStatus: string;
  energyStatus: string;
  surfaceSitesRevealed: boolean;
  resourceAnalysisReady: boolean;
  baseOperationalReady: boolean;
  siteTerrainBlendActive: boolean;
  resourceSiteGroundOffset: Record<string, number>;
  resourceSiteSlope: Record<string, number>;
  resourceSiteVisibilityScore: Record<string, number>;
  lagoonWaterAnimated: boolean;
  lagoonWaterFxCost: number;
  fissureThermalMapHint: boolean;
  surfaceShipSpeed: number;
  surfaceBoostActive: boolean;
  surfaceCruiseSpeed: number;
  surfaceBoostSpeed: number;
  surfaceAcceleration: number;
  surfaceDeceleration: number;
  surfaceTurnSpeed: number;
  surfaceHoverHeight: number;
  surfaceMaxBank: number;
  surfaceBoostFxIntensity: number;
  gamePaused: boolean;
  colonyStage: number;
  colonyReadiness: number;
  colonyReadinessBreakdown: Record<string, number>;
  nextColonyAction: string;
  baseSystemsReady: boolean;
  habitatOnline: boolean;
  habitatActivationStage: string;
  waterFound: boolean;
  mineralsFound: boolean;
  energyFound: boolean;
  baseNereidaOperational: boolean;
  saveExists: boolean;
  lastSaveTime: number;
  saveLoadStatus: string;
  collisionWorldReady: boolean;
  collisionStaticColliders: number;
  collisionDynamicColliders: number;
  collisionTriggers: number;
  collisionQueriesThisFrame: number;
  collisionQueryCandidates: number;
  collisionTimeMs: number;
  collisionRestoreCorrections: number;
  collisionDuplicateRegistrations: number;
  collisionResourcesReleased: number;
  saveWarning: string;
  scannerPulses: number;
  activeBeams: number;
  activeMissiles: number;
};

export class Diagnostics {
  readonly data: ArcaDiagnostics = {
    fps: 0,
    drawCalls: 0,
    triangles: 0,
    activeParticles: 0,
    entryParticles: 0,
    surfaceParticles: 0,
    activePOIs: 0,
    activeThreats: 0,
    dialogueQueueLength: 0,
    currentDialogueId: '',
    currentSpeaker: '',
    currentDialoguePriority: 'none',
    playedDialogueCount: 0,
    lastDialogueTrigger: '',
    dialoguePanelVisible: false,
    dialogueAwaitingInput: false,
    activeGLBCount: 0,
    activeSkinnedMeshCount: 0,
    activeAnimationMixerCount: 0,
    activeHighPolyAssets: [],
    duplicateMeshWarnings: [],
    heavyAssetWarnings: [],
    bundleWarning: '',
    estimatedDrawCalls: 0,
    inactiveUpdateSkippedCounts: {},
    lodActive: false,
    lodLevelCharacter: 'hidden',
    lodLevelCockpit: 'hidden',
    lodHiddenInactiveAssets: 0,
    atlasLodLevel: 'idle',
    arcaLodLevel: 'idle',
    shipLodLevel: 'idle',
    cockpitLodLevel: 'hidden',
    pilotLodLevel: 'hidden',
    activeTriangleEstimate: 0,
    assetPreloadQueue: [],
    assetLoadState: {},
    lazyLoadedAssets: [],
    preloadCompleted: false,
    mothershipStatus: 'idle',
    mothershipPath: '',
    mothershipMeshCount: 0,
    mothershipTriangles: 0,
    mothershipScale: 1,
    mothershipVisible: false,
    playerShipStatus: 'idle',
    playerShipPath: '',
    playerShipMeshCount: 0,
    playerShipTriangles: 0,
    playerShipScale: 1,
    playerShipVisible: false,
    shipPosition: [0, 0, 0],
    shipVelocity: [0, 0, 0],
    shipAltitudeHold: 0,
    shipGroundClearance: 0,
    shipAltitudeHoldTarget: 0,
    shipVerticalVelocity: 0,
    shipRealY: 0,
    shipPreviousY: 0,
    shipAltitudeHoldY: 0,
    shipTerrainY: 0,
    shipTerrainClearance: 0,
    parkedShipTerrainHeight: 0,
    parkedShipHullBottom: 0,
    parkedShipTerrainSeparation: 0,
    shipBoardingAnchorWorld: [0, 0, 0],
    shipBoardingHorizontalDistance: Number.POSITIVE_INFINITY,
    shipBoardingVerticalDifference: Number.POSITIVE_INFINITY,
    shipBoardingAvailable: false,
    shipParked: false,
    surfaceZone: 'space',
    shipParkingState: 'flight',
    parkedShipClearanceTarget: 0.12,
    shipVisualOscillationActive: true,
    shipAccessFConsumed: false,
    parkedShipRestoreChecked: false,
    parkedShipSaveCorrected: false,
    playerShipInstances: 1,
    shipAltitudeResetForce: 0,
    shipCameraJumpDistance: 0,
    verticalThrustActive: false,
    shipCollisionCollidersActive: 0,
    shipCollisionSweptDistance: 0,
    shipCollisionImpact: false,
    shipCollisionTimeOfImpact: 1,
    shipCollisionNormal: [0, 0, 0],
    shipCollisionPenetration: 0,
    shipCollisionObject: '',
    shipCollisionCandidates: 0,
    shipCollisionSubsteps: 1,
    shipCollisionLastSafePosition: [0, 0, 0],
    orbitalMarkerStatus: 'idle',
    orbitalMarkerPath: '',
    orbitalMarkerMeshCount: 0,
    orbitalMarkerMaterialCount: 0,
    orbitalMarkerTriangles: 0,
    orbitalMarkerObjectCount: 0,
    orbitalMarkerScale: 1,
    orbitalMarkerVisible: false,
    orbitalMarkerLodLevel: 'idle',
    descentPhase: 'idle',
    descentProgress: 0,
    descentHeat: 0,
    descentStability: 100,
    descentAltitude: 0,
    mission01Step: 'briefing',
    orbitalScanComplete: false,
    habitabilityScore: 0,
    missingDescentRequirements: [],
    descentAuthorized: false,
    descentBlockedReason: '',
    atlasCorridorDecoded: false,
    altitudeEstimate: 0,
    descentSpeedEstimate: 0,
    heatLevel: 0,
    turbulenceLevel: 0,
    entryFxIntensity: 0,
    entryStage: 'none',
    entryHeat: 0,
    entryIonization: 0,
    entryHaze: 0,
    entryBuffet: 0,
    entryAirDensity: 0,
    landingZoneActive: false,
    corridorPipsVisible: false,
    basinReveal: 0,
    landingImpactVisible: false,
    horizonTriangles: 0,
    cameraMode: 'external',
    previousShipCameraPreference: 'external',
    cameraFollowInitialized: false,
    cameraTargetCurrent: [0, 0, 0],
    cameraTargetPrevious: [0, 0, 0],
    cameraJumpDistance: 0,
    cameraFov: 0,
    lastCameraModeTransition: 'boot',
    cockpitActive: false,
    cockpitGlbStatus: 'loading',
    cockpitGlbPath: '/models/cockpit-interior.glb',
    cockpitGlbMeshCount: 0,
    cockpitGlbMaterialCount: 0,
    cockpitGlbTriangleCount: 0,
    cockpitGlbScale: 1,
    cockpitDrawCalls: 0,
    cockpitScreenUpdateRate: 0,
    cockpitScreenCount: 0,
    cockpitUpdateSkippedWhenInactive: 0,
    cockpitTextureUpdateCount: 0,
    cockpitScreenAnchorsVisible: false,
    cockpitDustParticleCount: 0,
    cockpitActiveDustParticles: 0,
    cockpitCanopyReflectionOpacity: 0,
    playerMode: 'SHIP_SPACE',
    onFootActive: false,
    characterGlbStatus: 'loading',
    characterMeshCount: 0,
    characterMaterialCount: 0,
    characterTriangleCount: 0,
    visibleCharacterMeshCount: 0,
    activeCharacterSkinnedMeshCount: 0,
    visibleCharacterTriangleCount: 0,
    loadedAnimationSources: 0,
    discardedDuplicateMeshes: 0,
    characterClipCount: 0,
    mixerActive: false,
    characterPerformanceWarning: '',
    characterAnimationClips: [],
    characterAnimation: 'none',
    characterMoveState: 'idle',
    characterInputVector: [0, 0],
    characterVelocity: [0, 0, 0],
    characterFacingYaw: 0,
    cameraYaw: 0,
    cameraPitch: 0.24,
    characterPosition: [0, 0, 0],
    characterSpeed: 0,
    characterGrounded: false,
    characterColliderActive: false,
    characterCollisionSlope: 0,
    characterCollisionContact: false,
    characterCollisionNormal: [0, 1, 0],
    characterCollisionPenetration: 0,
    characterCollisionIterations: 0,
    characterCollisionCandidates: 0,
    characterCollisionLastSafePosition: [0, 0, 0],
    liftRideState: 'idle',
    characterOnLift: false,
    characterFootLockActive: false,
    liftProgress: 0,
    liftContactShadowActive: false,
    boardingAnimationState: 'idle',
    nearestInteractionTarget: '',
    nearestInteractionAction: 'none',
    interactionDistance: Number.POSITIVE_INFINITY,
    insideShip: true,
    rampState: 'retracted',
    shipExitAvailable: false,
    shipAccessAvailable: false,
    inputMode: 'space-flight',
    lastInputKey: '',
    lastInputAction: 'none',
    actionConsumedBy: 'none',
    canToggleCamera: true,
    cameraToggleAvailable: true,
    mapOpen: false,
    pauseOpen: false,
    currentPhase: 'space',
    currentMissionId: 'mission-01-search-home',
    currentMissionStep: 'boot',
    objectiveText: '',
    nextAction: '',
    currentGuideTarget: '',
    guideTargetName: '',
    guideTargetDistance: Number.POSITIVE_INFINITY,
    guideDirection: 0,
    guideMode: 'hidden',
    guideDistance: Number.POSITIVE_INFINITY,
    guideVisible: false,
    guideOffscreen: false,
    guideSource: 'ObjectiveResolver',
    playerInputMode: 'flight',
    surfaceModeActive: false,
    mission02Step: 'inactive',
    mission03Started: false,
    mission03Step: 'inactive',
    communicationCalibrated: false,
    communicationCalibrationProgress: 0,
    mission03SignalState: 'inactive',
    relayBeaconPlaced: false,
    relayRange: 0,
    signalStability: 0,
    playerInRelayRange: false,
    relaySignalFlowActive: false,
    translationState: 'noSignal',
    translationProgress: 0,
    translatedFragments: 0,
    pleyadanContactEstablished: false,
    hologramWarningActive: false,
    atlasTranslationMatrixUnlocked: false,
    galacticThreatKnown: false,
    orbitalDefenseRequired: false,
    mission04Unlocked: false,
    mission03Completed: false,
    mission04Started: false,
    mission04Step: 'inactive',
    defenseNetworkState: 'offline',
    defensiveBeaconsPlaced: [],
    defenseSyncProgress: 0,
    activeDefenseBeaconTarget: 0,
    threatSignatureDetected: false,
    mission04Completed: false,
    mission05Unlocked: false,
    defenseLinksActive: false,
    defenseLinksUnstable: false,
    defenseLinksOnline: false,
    defenseNetworkVisible: false,
    threatSignatureWorldVisible: false,
    activeDefenseLinkCount: 0,
    mission05Started: false,
    mission05Step: 'inactive',
    probeState: 'hidden',
    interferenceActive: false,
    activeEchoIndex: -1,
    echoesResolved: 0,
    counterSignalProgress: 0,
    probeRetreated: false,
    firstHostileContactConfirmed: false,
    mission06Unlocked: false,
    mission06Started: false,
    mission06Step: 'inactive',
    interferenceResidueAnalyzed: false,
    cloakingMatrixCalibrated: false,
    cloakingProjectorsPlaced: [],
    cloakingProjectorsCalibrated: [],
    cloakingSyncProgress: 0,
    cloakingFieldOnline: false,
    nereidaSignatureReduced: false,
    mission06Completed: false,
    mission07Unlocked: false,
    mission07Started: false,
    mission07Step: 'inactive',
    subsurfaceSignalAnalyzed: false,
    atlasFractureRevealed: false,
    atlasEchoNodesScanned: [],
    atlasSeedArchiveUnlocked: false,
    atlasSeedArchiveActivated: false,
    seedWorldRevealed: false,
    mission07Completed: false,
    mission08Unlocked: false,
    mission08Started: false,
    mission08Step: 'inactive',
    fractureTraceAnalyzed: false,
    signalFractureRevealed: false,
    fractureNodesStabilized: [],
    signalPurgeProgress: 0,
    signalFractureContained: false,
    coalitionTraceResidual: false,
    mission08Completed: false,
    mission09Unlocked: false,
    mission09Started: false,
    mission09Step: 'inactive',
    residualTraceAnalyzed: false,
    auroraRouteDecoded: false,
    auroraRouteBeaconsScanned: [],
    currentAuroraSector: 0,
    auroraSignalStrength: 1,
    auroraSectorDiscovered: false,
    mission09Completed: false,
    mission10Unlocked: false,
    activeAuroraSectorCount: 0,
    auroraSectorStreamingActive: false,
    premiumVisualsEnabled: false,
    premiumVisualsMode: 'fallback',
    premiumVisualQuality: 'medium',
    premiumParticleCount: 0,
    premiumVisualDrawCalls: 0,
    premiumVisualWarnings: [],
    webgpuAvailable: false,
    tslAvailable: false,
    premiumAutoQualityEnabled: true,
    premiumFpsAverage: 60,
    premiumQualityDowngradeReason: '',
    premiumLastQualityChangeAt: 0,
    renderProfile: 'high',
    activePointLights: 0,
    registeredPointLights: 0,
    mission13Started: false,
    mission13Step: 'inactive',
    auroraStormAlertAcknowledged: false,
    auroraGeneratorSecured: false,
    auroraGeneratorProgress: 0,
    auroraAntennaAnchorsSecured: [],
    auroraAntennaOnline: false,
    auroraShieldCharge: 0,
    auroraShieldOnline: false,
    auroraStormFrontIntensity: 0,
    auroraStormEnergyStability: 100,
    auroraStormInterference: 0,
    mission13Completed: false,
    mission14Unlocked: false,
    mission14Started: false,
    mission14Step: 'inactive',
    coalitionTraceInspections: [false, false, false],
    coalitionSignatureAnalyzed: false,
    coalitionPowerNodePurged: false,
    coalitionCommsNodePurged: false,
    coalitionHiddenNodeLocated: false,
    coalitionTraceSampleRecovered: false,
    coalitionReverseTriangulationComplete: false,
    coalitionContamination: 0,
    coalitionHostileTriangulation: 0,
    coalitionSignalIntensity: 0,
    coalitionPurgedNodes: 0,
    coalitionPhaseProgress: 0,
    coalitionTraceVisualActive: false,
    mission14Completed: false,
    mission15Unlocked: false,
    mission15Started: false,
    mission15Step: 'inactive',
    auroraRoutineComplete: false,
    auroraModuleSealed: false,
    auroraModuleReleased: false,
    auroraCoordinatedFailureConfirmed: false,
    auroraParasiteStates: ['hidden', 'hidden', 'hidden'],
    mission15Sequence: [2, 0, 3, 1],
    mission15SequenceVisualStep: 1,
    mission15SequenceLogicalStep: 0,
    mission15ExpectedSymbol: -1,
    mission15HighlightedSymbol: -1,
    mission15InteractedSymbol: -1,
    mission15SequenceMatched: 0,
    mission15SequenceInputConsumed: false,
    mission15SequenceInputLockRemaining: 0,
    mission15SequenceErrorActive: false,
    mission15SequenceFeedback: 'idle',
    mission15SequenceCompleted: false,
    auroraParasitesFound: 0,
    auroraParasitesDisabled: 0,
    auroraModulePressure: 100,
    auroraCompromisedSystems: 0,
    auroraCentralOverload: 0,
    auroraCentralOverloadResolved: false,
    auroraSabotageSignalIntensity: 0,
    auroraSabotagePhaseProgress: 0,
    auroraParasiteAnalyzed: false,
    auroraSabotageVisualActive: false,
    mission15Completed: false,
    mission16Unlocked: false,
    mission21Started: false,
    mission21Step: 'inactive',
    transmissionChannelsAligned: [false, false, false],
    transmissionDecoded: false,
    capitalShipDetected: false,
    capitalSignatureAnalyzed: false,
    ultimatumReceived: false,
    coalitionResponseTone: 'none',
    enclaveChannelsRestored: [false, false, false],
    demonstrationObserved: false,
    attackRoutesClassified: [false, false, false],
    pleyadianNetworkActivated: false,
    simultaneousAssaultDetected: false,
    mission21Completed: false,
    mission22Unlocked: false,
    coalitionCapitalPresenceBuilt: false,
    coalitionCapitalPresenceVisible: false,
    coalitionCapitalAttackable: false,
    coalitionRemoteBeaconDestroyed: false,
    coalitionAttackRoutesVisible: 0,
    mission21InterferenceLevel: 0,
    mission22Started: false,
    mission22Step: 'inactive',
    mission22AuroraIntegrity: 84,
    mission22NereidaIntegrity: 80,
    mission22OrbitalIntegrity: 76,
    mission22InitialEnergyFront: 'none',
    mission22InitialDefenseFront: 'none',
    mission22InitialCommsFront: 'none',
    mission22AuroraFrontDefended: false,
    mission22NereidaFrontDefended: false,
    mission22OrbitalRelaysProtected: [false, false, false],
    mission22CrossFrontCrisisManaged: false,
    mission22SupportPriority: 'none',
    mission22JointNetworkRestored: false,
    mission22CoordinationNodesDetected: [false, false, false],
    mission22FinalPressureSurvived: false,
    mission22Completed: false,
    mission23Unlocked: false,
    mission22VisualBuilt: false,
    mission22VisualVisible: false,
    mission22VisibleRelayCount: 0,
    mission22VisibleNodeCount: 0,
    mission22JointNetworkVisible: false,
    mission23Started: false,
    mission23Step: 'inactive',
    mission23TargetOrder: [],
    jointForcesSynchronized: false,
    jammerTriangulationReadings: [false, false, false],
    jammerNodeDestroyed: false,
    platformDefensesDisabled: false,
    platformEnergyDisabled: false,
    mission23PlatformMethod: 'none',
    logisticsPlatformDestroyed: false,
    jumpBeaconAnchorsDisabled: [false, false, false],
    jumpBeaconDestroyed: false,
    escapeCompleted: false,
    enemyRouteRecovered: false,
    returnToArkConfirmed: false,
    mission23Completed: false,
    mission24Unlocked: false,
    mission23JointEnergy: 0,
    mission23LockDegraded: false,
    mission23PlatformBuilt: false,
    mission23PlatformVisible: false,
    mission23PlatformActiveModules: 0,
    mission23JumpBeaconBuilt: false,
    mission23JumpBeaconVisible: false,
    mission23VisibleAnchorCount: 0,
    mission23ActiveHostiles: 0,
    mission23EscapeDistance: 0,
    mission24Started: false,
    mission24Step: 'inactive',
    returnRouteDecoded: false,
    launchPrepared: false,
    shipBoardedForReturn: false,
    ignitionComplete: false,
    takeoffComplete: false,
    lowAtmosphereComplete: false,
    cloudLayerComplete: false,
    midAtmosphereComplete: false,
    upperAtmosphereComplete: false,
    vacuumTransitionComplete: false,
    orbitalInsertionComplete: false,
    orbitStabilized: false,
    mission24ArkReached: false,
    mission24ArkSystemsAssessed: 0,
    mission24EnclaveLinksRestored: 0,
    mission24ArkSystemsPrepared: 0,
    mission24PleyadianNodesIntegrated: 0,
    civilianSheltersPrepared: false,
    alliedForcesAssembled: false,
    startingSectorRevisited: false,
    defenseRehearsalComplete: false,
    finalFleetDetected: false,
    finalFormationEntered: false,
    mission24Completed: false,
    mission25Unlocked: false,
    mission24Altitude: 0,
    mission24WorldClearance: 0,
    mission24VerticalSpeed: 0,
    mission24HorizontalSpeed: 0,
    mission24Pressure: 101.3,
    mission24Density: 1,
    mission24Wind: 1,
    mission24CloudOpacity: 0,
    mission24StarOpacity: 0,
    mission24Curvature: 0,
    mission24OrbitalStability: 0,
    mission24MaxFrameDisplacement: 0,
    mission24Checkpoint: 'surface',
    mission24AtmosphereBuilt: false,
    mission24CloudLayerVisible: false,
    mission24PlanetLimbVisible: false,
    mission24NetworkBuilt: false,
    mission24NetworkVisible: false,
    mission24PleyadianNodesVisible: 0,
    mission24RehearsalTargets: 0,
    mission24RehearsalTargetsVisible: false,
    mission24FinalFleetVisible: false,
    mission24FinalFleetAttackable: false,
    mission24ActiveTimers: 0,
    mission24MothershipUuid: '',
    mission24MothershipInstances: 1,
    mission25Started: false,
    mission25State: 'inactive',
    mission25DefensePhase: 0,
    mission25Wave: 0,
    mission25ArkIntegrity: 100,
    mission25SystemIntegrities: [100, 100, 100],
    mission25InheritedM22Priority: 'none',
    mission25InheritedM23Support: false,
    mission25CommandNodesDestroyed: [false, false, false],
    mission25CommandCoreIntegrity: 100,
    mission25ActiveEnemies: 0,
    mission25EnemiesDestroyed: 0,
    mission25BattleState: 'inactive',
    mission25EndingStarted: false,
    mission25EndingCompleted: false,
    mission25Completed: false,
    chapterCompleted: false,
    mission25DefenseNetworkBuilt: false,
    mission25DefenseNetworkVisible: false,
    mission25CommandBuilt: false,
    mission25CommandVisible: false,
    mission25ActiveTimers: 0,
    mission25MothershipUuid: '',
    mission25MothershipInstances: 1,
    mission25PlayerShipInstances: 1,
    mission25MusicCue: 'none',
    mission25SaveRestored: false,
    mission12Started: false,
    mission12Step: 'inactive',
    auroraFirstCrewAuthorized: false,
    auroraLifeSupportHumanReady: false,
    auroraHabitationConfigured: false,
    auroraLandingZoneMarked: false,
    auroraCrewCapsuleLanded: false,
    auroraFirstCrewDisembarked: false,
    auroraHumanLoadProgress: 0,
    auroraHumanLoadRecalibrated: false,
    auroraRecalibrationProgress: 0,
    auroraInhabitedCoreStable: false,
    auroraFirstNightRecorded: false,
    mission12Completed: false,
    mission13Unlocked: false,
    currentCrewCount: 0,
    habitationStability: 100,
    mission11Started: false,
    mission11Step: 'inactive',
    auroraCoreDiagnosticComplete: false,
    auroraSecondModuleDeployed: false,
    auroraEnergyLinkOnline: false,
    auroraWaterFilterInstalled: false,
    auroraWaterFlowCalibrated: false,
    auroraCultivationBedPrepared: false,
    auroraBioTrialStarted: false,
    auroraImpactAssessmentComplete: false,
    auroraCoreOperational: false,
    mission11Completed: false,
    mission12Unlocked: false,
    mission10Started: false,
    mission10Step: 'inactive',
    auroraInitialSurveyComplete: false,
    auroraWaterAnalyzed: false,
    auroraSoilAnalyzed: false,
    auroraAtmosphereAnalyzed: false,
    auroraBioSafetyChecked: false,
    auroraSettlementSiteMarked: false,
    auroraModuleDeployed: false,
    auroraModuleOperational: false,
    auroraStabilizationProgress: 0,
    mission10Completed: false,
    mission11Unlocked: false,
    currentAuroraTravelSegment: 'inactive',
    auroraMusicSegment: 'none',
    auroraEnvironmentalEvent: 'none',
    auroraEnvironmentalEventActive: false,
    auroraStormIntensity: 0,
    auroraWindIntensity: 0,
    auroraFogIntensity: 0,
    auroraCinematicTravelActive: false,
    auroraRevealActive: false,
    signalFractureVisualActive: false,
    auroraRevealVisualActive: false,
    currentMusicState: 'space',
    currentMusicTrack: 'none',
    activeMusicLayers: [],
    engineAudioState: 'off',
    propulsionIntensity: 0,
    hoverAudioIntensity: 0,
    verticalThrustAudioIntensity: 0,
    boostAudioIntensity: 0,
    groundWashAudioIntensity: 0,
    spaceCruiseAudioActive: false,
    atmosphericAudioActive: false,
    interferenceAudioActive: false,
    dialogueDuckingActive: false,
    musicDuckingAmount: 0,
    missingAudioAssets: [],
    missingMusicAssets: [],
    commanderVoiceEnabled: false,
    voiceManifestLoaded: false,
    currentVoiceDialogueId: '',
    voicePlaying: false,
    voiceMissingCount: 0,
    pleyadanVoiceEnabled: false,
    commanderVoiceAvailableCount: 0,
    pleyadanVoiceAvailableCount: 0,
    voiceVolume: 0,
    voiceDuckingActive: false,
    lastVoiceError: '',
    footstepAudioActive: false,
    footstepMode: 'none',
    lastFootstepTime: 0,
    footstepSurface: 'dry-alien-ground',
    footstepMissingAssets: [],
    waterStatus: 'unknown',
    mineralStatus: 'unknown',
    energyStatus: 'unknown',
    surfaceSitesRevealed: false,
    resourceAnalysisReady: false,
    baseOperationalReady: false,
    siteTerrainBlendActive: false,
    resourceSiteGroundOffset: {},
    resourceSiteSlope: {},
    resourceSiteVisibilityScore: {},
    lagoonWaterAnimated: false,
    lagoonWaterFxCost: 0,
    fissureThermalMapHint: false,
    surfaceShipSpeed: 0,
    surfaceBoostActive: false,
    surfaceCruiseSpeed: 0,
    surfaceBoostSpeed: 0,
    surfaceAcceleration: 0,
    surfaceDeceleration: 0,
    surfaceTurnSpeed: 0,
    surfaceHoverHeight: 0,
    surfaceMaxBank: 0,
    surfaceBoostFxIntensity: 0,
    gamePaused: false,
    colonyStage: 0,
    colonyReadiness: 0,
    colonyReadinessBreakdown: {},
    nextColonyAction: '',
    baseSystemsReady: false,
    habitatOnline: false,
    habitatActivationStage: 'offline',
    waterFound: false,
    mineralsFound: false,
    energyFound: false,
    baseNereidaOperational: false,
    saveExists: false,
    lastSaveTime: 0,
    saveLoadStatus: 'idle',
    collisionWorldReady: false,
    collisionStaticColliders: 0,
    collisionDynamicColliders: 0,
    collisionTriggers: 0,
    collisionQueriesThisFrame: 0,
    collisionQueryCandidates: 0,
    collisionTimeMs: 0,
    collisionRestoreCorrections: 0,
    collisionDuplicateRegistrations: 0,
    collisionResourcesReleased: 0,
    saveWarning: '',
    scannerPulses: 0,
    activeBeams: 0,
    activeMissiles: 0
  };

  private frameTimeAccumulator = 0;

  private frameCount = 0;

  private publishAccumulator = Number.POSITIVE_INFINITY;

  /**
   * Whether the `update` about to run with this delta will publish a snapshot.
   *
   * The published object only changes every 100 ms, so building the full
   * diagnostics patch on frames that will not publish is pure waste — the
   * caller polls this and assembles the heavy patch only when it can be seen.
   * Frame-rate accounting and the renderer counters still run every frame.
   */
  patchDue(delta: number): boolean {
    // Must predict the frame that will publish, not the state after the last
    // one: `update` resets the accumulator whenever it publishes, so a getter
    // reading the current value would report "not due" on every later frame
    // and the snapshot would freeze at its boot values.
    return delta === 0 || this.publishAccumulator + delta >= PUBLISH_INTERVAL_SECONDS;
  }

  update(renderer: THREE.WebGLRenderer, delta: number, patch: Partial<ArcaDiagnostics>): void {
    this.frameTimeAccumulator += delta;
    this.frameCount += 1;

    if (this.frameTimeAccumulator >= 0.5) {
      this.data.fps = Math.round(this.frameCount / this.frameTimeAccumulator);
      this.frameTimeAccumulator = 0;
      this.frameCount = 0;
    }

    this.data.drawCalls = renderer.info.render.calls;
    this.data.triangles = renderer.info.render.triangles;
    Object.assign(this.data, patch);
    this.publishAccumulator += delta;
    if (delta === 0 || this.publishAccumulator >= PUBLISH_INTERVAL_SECONDS) {
      window.__arcaDiagnostics = { ...this.data };
      this.publishAccumulator = 0;
    }
  }
}

declare global {
  interface Window {
    __arcaDiagnostics?: ArcaDiagnostics;
  }
}
